---
exclude_paths:
  - "**/*_test.go"
  - "**/*.d.ts"
  - "**/*.pb.go"
  - "**/Dockerfile"
  - "service/importer/assets/*.go"
  - "cmd/service/assets/*.go"
  - "cmd/service/tests/**/*"
  - "service-test/**"
  - "docs/**"
  - "**/vendor/**/*"
