exclude_patterns:
  - "**/*_test.go"
  - "**/*.d.ts"
  - "**/*.pb.go"
  - "service/importer/assets/*.go"
  - "cmd/service/assets/*.go"
  - "cmd/service/tests/**/*"
  - "docs/**/*"
  - "**/vendor/"
plugins:
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true

checks:
  return-statements:
    config:
      threshold: 6
