exclude_patterns:
  - "**/*_test.go"
  - "**/*.d.ts"
  - "**/*.pb.go"
  - "service/importer/assets/*.go"
  - "cmd/service/assets/*.go"
  - "cmd/service/tests/**/*"
  - "docs/**/*"
plugins:
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
