run:
  tests: true
  skip-files:
    - ".*.pb.go$"

linters-settings:
  govet:
    check-shadowing: false
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 20
  maligned:
    suggest-new: true
  misspell:
    locale: US

issues:
  exclude:
    - "ineffective break statement. Did you mean to break out of the outer loop"

  exclude-rules:
    - path: ext/xvalidator/validator.go
      linters:
        - golint
      text: "exported var Translator should have its own declaration"
    - path: hash/structhash/structhash_test.go
      linters:
        - maligned

linters:
  disable-all: true
  enable: 
    - bodyclose
    - deadcode
    - dogsled
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - maligned
    - misspell
    - nakedret
    - scopelint
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
