# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

# dependencies of ./scripts.
required = [
  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc",
  "github.com/go-bindata/go-bindata/go-bindata",
  "github.com/vektra/mockery/cmd/mockery"
]

[[constraint]]
  branch = "master"
  name = "github.com/grpc-ecosystem/go-grpc-middleware"

[[constraint]]
  version = "1.0.6"
  name = "github.com/sirupsen/logrus"

[[constraint]]
  branch = "master"
  name = "github.com/asaskevich/govalidator"

[[constraint]]
  branch = "master"
  name = "github.com/cnf/structhash"

[[constraint]]
  branch = "master"
  name = "github.com/docker/docker"

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  branch = "master"
  name = "github.com/logrusorgru/aurora"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/viper"

[[constraint]]
  branch = "master"
  name = "github.com/syndtr/goleveldb"

[[constraint]]
  branch = "master"
  name = "github.com/xeipuuv/gojsonschema"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[override]]
  branch = "master"
  name = "google.golang.org/grpc"

[[constraint]]
  branch = "master"
  name = "gopkg.in/AlecAivazis/survey.v1"

[[constraint]]
  branch = "master"
  name = "gopkg.in/src-d/go-git.v4"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"