version: 2

onlyTagProd: &onlyTagProd
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/
onlyBranchDev: &onlyBranchDev
  filters:
    branches:
      only:
        - 237-circleci-dev-release
transient: &transient
  filters:
    tags:
      only: /.*/
runOnMachine: &runOnMachine
  machine:
    docker_layer_caching: true
  working_directory: ~/.go_workspace/src/github.com/mesg-foundation/core

jobs:
  "build_docker":
    <<: *runOnMachine
    steps:
      - checkout
      - run: docker pull mesg/core:latest
      - run: docker build -t mesg/core:$CIRCLE_SHA1 .

  "test":
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/mesg-foundation/core
    steps:
      - checkout
      - setup_remote_docker
      - run: go get -t ./...
      - run: docker swarm init
      - run: docker pull nginx
      - run: docker pull alpine
      - run: env CORE.IMAGE=mesg/core:$CIRCLE_SHA1 go test -timeout 180s -p 1 -coverprofile=coverage.txt ./...
      - run: bash <(curl -s https://codecov.io/bash)

  "publish_docker_dev":
    <<: *runOnMachine
    steps:
      - checkout
      - run: docker pull mesg/core:dev
      - run: docker build -t mesg/core:dev .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push mesg/core:dev

  "publish_docker_prod":
    <<: *runOnMachine
    steps:
      - checkout
      - run: docker pull mesg/core:latest
      - run: docker build -t mesg/core:$CIRCLE_TAG -t mesg/core:latest .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push mesg/core:$CIRCLE_TAG
      - run: docker push mesg/core:latest

  "release_cli_dev":
    <<: *runOnMachine
    steps:
      - checkout
      - run: scripts/build-cli.sh dev
      - run: go get -u github.com/tcnksm/ghr
      - run: ghr -u mesg-foundation -r core -delete -prerelease -b "Warning - this is a developer release, use it only if you know what are doing. You have to set the env variable \`export CORE.IMAGE=mesg/core:dev\`" release-dev ./bin

  "release_cli_prod":
    <<: *runOnMachine
    steps:
      - checkout
      - run: scripts/build-cli.sh $CIRCLE_TAG
      - run: go get -u github.com/tcnksm/ghr
      - run: ghr -u mesg-foundation -r core -delete $CIRCLE_TAG ./bin

workflows:
  version: 2
  build_n_deploy:
    jobs:
      - "build_docker":
          <<: *transient
      - "test":
          <<: *transient
          requires:
            - "build_docker"
      - "publish_docker_dev":
          <<: *onlyBranchDev
          requires:
            - "test"
      - "release_cli_dev":
          <<: *onlyBranchDev
          requires:
            - "publish_docker_dev"
      - "publish_docker_prod":
          <<: *onlyTagProd
          requires:
            - "test"
      - "release_cli_prod":
          <<: *onlyTagProd
          requires:
            - "publish_docker_prod"
