version: 2

onlyTagProd: &onlyTagProd
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/
onlyBranchDev: &onlyBranchDev
  filters:
    branches:
      only:
        - dev
transient: &transient
  filters:
    tags:
      only: /.*/
runOnMachine: &runOnMachine
  machine:
    docker_layer_caching: true
  working_directory: ~/.go_workspace/src/github.com/mesg-foundation/core
runOnDocker: &runOnDocker
  docker:
    - image: circleci/golang:1.10
  working_directory: /go/src/github.com/mesg-foundation/core

jobs:
  "build_docker":
    <<: *runOnMachine
    steps:
      - checkout
      - run: docker build -t mesg/core:$CIRCLE_SHA1 --build-arg version="dev build `echo $CIRCLE_SHA1 | cut -c1-7`" .

  "unit_test":
    <<: *runOnDocker
    steps:
      - checkout
      - run: go get -t ./...
      - run: go test -coverprofile=coverage.txt ./...
      - run: bash <(curl -s https://codecov.io/bash)
  
  "integration_test":
    <<: *runOnDocker
    steps:
      - checkout
      - setup_remote_docker
      - run: go get -t ./...
      - run: docker swarm init
      - run: docker build -t sleep docker-images/sleep/
      - run: docker build -t http-server docker-images/http-server/
      - run: env MESG_CORE_IMAGE=mesg/core:$CIRCLE_SHA1 go test -tags=integration -timeout 180s -p 1

  "publish_docker_dev":
    <<: *runOnMachine
    steps:
      - checkout
      - run: docker build -t mesg/core:dev --build-arg version="dev build `echo $CIRCLE_SHA1 | cut -c1-7`" .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push mesg/core:dev

  "publish_docker_prod":
    <<: *runOnMachine
    steps:
      - checkout
      - run: docker build -t mesg/core:$CIRCLE_TAG -t mesg/core:latest --build-arg version=$CIRCLE_TAG .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push mesg/core:$CIRCLE_TAG
      - run: docker push mesg/core:latest

  "release_cli_dev":
    <<: *runOnDocker
    steps:
      - checkout
      - run: scripts/build-cli.sh "dev build `echo $CIRCLE_SHA1 | cut -c1-7`"
      - run: go get -u github.com/tcnksm/ghr
      - run: ghr -u mesg-foundation -r core -delete -prerelease -b "Warning - this is a developer release, use it only if you know what are doing. Make sure to pull the latest \`mesg/core:dev\` image. \`\`\`docker pull mesg/core:dev\`\`\`" release-dev ./bin

  "release_cli_prod":
    <<: *runOnDocker
    steps:
      - checkout
      - run: scripts/build-cli.sh $CIRCLE_TAG
      - run: go get -u github.com/tcnksm/ghr
      - run: ghr -u mesg-foundation -r core -delete $CIRCLE_TAG ./bin

workflows:
  version: 2
  build_n_deploy:
    jobs:
      - "unit_test":
          <<: *transient
      - "build_docker":
          <<: *transient
      - "integration_test":
          <<: *transient
          requires:
            - "build_docker"
      - "publish_docker_dev":
          <<: *onlyBranchDev
          requires:
            - "unit_test"
      - "release_cli_dev":
          <<: *onlyBranchDev
          requires:
            - "publish_docker_dev"
      - "publish_docker_prod":
          <<: *onlyTagProd
          requires:
            - "test"
      - "release_cli_prod":
          <<: *onlyTagProd
          requires:
            - "publish_docker_prod"
