version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/mesg-foundation/core
    steps:
      - checkout
      - setup_remote_docker
      - run: go get -t ./...
      - run: docker swarm init
      - run: env DAEMON.IMAGE=mesg/daemon:local go test -timeout 60s -p 1 -coverprofile=coverage.txt ./...
      - run: bash <(curl -s https://codecov.io/bash)

  cli_build_deploy:
    machine:
      docker_layer_caching: true
    working_directory: ~/.go_workspace/src/github.com/mesg-foundation/core
    steps:
      - checkout
      - run: go get ./...
      - run: go get github.com/karalabe/xgo
      - run: mkdir bin
      - run: cd bin; xgo --targets=darwin/386,darwin/amd64,linux/386,linux/amd64,windows/386,windows/amd64 -out mesg-core ../cli
      - run: sudo chmod +x ./bin/*
      - run: go get -u github.com/tcnksm/ghr
      - run: ghr -u mesg-foundation -r core -delete release-dev ./bin

  docker_build_deploy:
    machine:
      docker_layer_caching: true
    working_directory: ~/.go_workspace/src/github.com/mesg-foundation/core
    steps:
      - checkout
      - run: docker build -t mesg/daemon .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push mesg/daemon

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - test
      - docker_build_deploy:
          requires:
            - test
          filters:
            branches:
              only: dev
      - cli_build_deploy:
          requires:
            - test
          filters:
            branches:
              only: dev
