version: 2

run_on_machine: &run_on_machine
  machine:
    docker_layer_caching: false

run_on_docker: &run_on_docker
  docker:
    - image: circleci/golang:1.13.0

restore_go_mod_cache: &restore_go_mod_cache
  - restore_cache:
      keys:
        - go-mod-cache-{{ checksum "go.sum" }}

save_go_mod_cache: &save_go_mod_cache
  - save_cache:
      key: go-mod-cache-{{ checksum "go.sum" }}
      paths:
        - /go/pkg/mod

go_cache_dir: &go_cache_dir /tmp/go/cache

restore_go_cache: &restore_go_cache
  - restore_cache:
      keys:
        - go-cache-{{ .Branch }}-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}
        - go-cache-{{ .Branch }}
        - go-cache

save_go_cache: &save_go_cache
  - save_cache:
      key: go-cache-{{ .Branch }}-{{ .BuildNum }}
      paths:
        - *go_cache_dir

jobs:
  "test":
    <<: *run_on_machine
    environment:
      - GOCACHE: *go_cache_dir
    steps:
      - checkout
      - run: docker swarm init
      - <<: *restore_go_cache
      - <<: *restore_go_mod_cache
      - run: make test e2e
      - <<: *save_go_mod_cache
      - <<: *save_go_cache
      - run: bash <(curl -s https://codecov.io/bash)

  "lint":
    docker:
      - image: golangci/golangci-lint:v1.18
    environment:
      - GOCACHE: *go_cache_dir
    steps:
      - checkout
      - <<: *restore_go_mod_cache
      - run: make lint

  "publish_docker_dev":
    <<: *run_on_machine
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: make docker-publish-dev version=`echo $CIRCLE_SHA1 | cut -c1-7`

  "publish_docker_prod":
    <<: *run_on_machine
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: make docker-publish version=$CIRCLE_TAG

workflows:
  version: 2

  pull_request:
    jobs:
      - "lint":
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore:
                - "dev"
                - "master"
      - "test":
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore:
                - "dev"
                - "master"

  release_dev:
    jobs:
      - "lint":
          filters:
            tags:
              ignore: /.*/
            branches:
              only: dev
      - "test":
          filters:
            tags:
              ignore: /.*/
            branches:
              only: dev
      - "publish_docker_dev":
          requires:
            - "test"
            - "lint"

  test_prod:
    jobs:
      - "test":
          filters:
            tags:
              ignore: /.*/
            branches:
              only: master
      - "lint":
          filters:
            tags:
              ignore: /.*/
            branches:
              only: master

  release_prod:
    jobs:
      - "lint":
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - "test":
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - "publish_docker_prod":
          requires:
            - "test"
            - "lint"
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
