version: 2

onlyTagProd: &onlyTagProd
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/
onlyBranchDev: &onlyBranchDev
  filters:
    branches:
      only:
        - dev
transient: &transient
  filters:
    tags:
      only: /.*/
runOnMachine: &runOnMachine
  machine:
    docker_layer_caching: true
  working_directory: ~/.go_workspace/src/github.com/mesg-foundation/core
runOnDocker: &runOnDocker
  docker:
    - image: circleci/golang:1.10
  working_directory: /go/src/github.com/mesg-foundation/core

jobs:
  "test":
    <<: *runOnDocker
    steps:
      - checkout
      - setup_remote_docker
      - run: go get -t ./...
      - run: docker swarm init
      - run: docker build -t sleep docker-images/sleep/
      - run: docker build -t http-server docker-images/http-server/
      - run: go test -timeout 180s -p 1 -coverprofile=coverage.txt ./...
      - run: bash <(curl -s https://codecov.io/bash)
  "release_cli_dev":
    <<: *runOnDocker
    steps:
      - checkout
      - run: scripts/build-cli.sh "dev build `echo $CIRCLE_SHA1 | cut -c1-7`"
      - run: go get -u github.com/tcnksm/ghr
      - run: ghr -u mesg-foundation -r core -delete -prerelease -b "Warning - this is a developer release, use it only if you know what are doing. Make sure to pull the latest \`mesg/core:dev\` image. \`\`\`docker pull mesg/core:dev\`\`\`" release-dev ./bin

  "release_cli_prod":
    <<: *runOnDocker
    steps:
      - checkout
      - run: scripts/build-cli.sh $CIRCLE_TAG
      - run: go get -u github.com/tcnksm/ghr
      - run: ghr -u mesg-foundation -r core -delete $CIRCLE_TAG ./bin

workflows:
  version: 2
  build_n_deploy:
    jobs:
      - "test":
          <<: *transient
          requires:
            - "build_docker"
      - "release_cli_dev":
          <<: *onlyBranchDev
          requires:
            - "test"
      - "release_cli_prod":
          <<: *onlyTagProd
          requires:
            - "test"
