# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: /go/src/github.com/mesg-foundation/application
    steps:
      - checkout
      - setup_remote_docker
      # - run: ls -l /var/run/docker.sock
      # - run: sudo chmod 777 /var/run/docker.sock # TODO find another way to access the socket
      # - run: docker ps
      # specify any ecbash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...