version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/mesg-foundation/core
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: v1-mesg-core-test
      - run: go get -v -u -t ./...
      - save_cache:
          key: v1-mesg-core-test
          paths:
            - /go/bin
            - /go/pkg
            - /go/src
      - run: go test -coverprofile=coverage.txt -v ./...
      - run: bash <(curl -s https://codecov.io/bash)

  build_deploy:
    machine:
      docker_layer_caching: true
    working_directory: ~/.go_workspace/src/github.com/mesg-foundation/core
    steps:
      - checkout
      - restore_cache:
          key: v1-mesg-core-build-deploy
      - run: go get -v -u -t ./...
      - run: go get -v -u github.com/karalabe/xgo
      - save_cache:
          key: v1-mesg-core-build-deploy
          paths:
            - ~/.go_workspace/bin
            - ~/.go_workspace/pkg
            - ~/.go_workspace/src
      - run: mkdir bin
      - run: cd bin; xgo --targets=darwin/386,darwin/amd64,linux/386,linux/amd64,windows/386,windows/amd64 ../cli
      - run: sudo chmod +x ./bin/*
      - store_artifacts:
          path: ./bin
      - run: go get -u github.com/tcnksm/ghr
      - run: ghr -u mesg-foundation -r core -delete dev ./bin

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - test
      - build_deploy:
          requires:
            - test
          filters:
            branches:
              only: dev
