version: 2

runOnMachine: &runOnMachine
  machine:
    docker_layer_caching: true
  working_directory: ~/.go_workspace/src/github.com/mesg-foundation/core

runOnDocker: &runOnDocker
  docker:
    - image: circleci/golang:1.11
  working_directory: /go/src/github.com/mesg-foundation/core

jobs:
  "test":
    <<: *runOnDocker
    steps:
      - checkout
      - setup_remote_docker
      - run: docker swarm init
      - run: docker build -t sleep docker-images/sleep/
      - run: docker build -t http-server docker-images/http-server/
      - run: mkdir -p ~/.mesg && ln -s /go/src/github.com/mesg-foundation/core/systemservices/sources ~/.mesg/systemservices
      - run: go test -v -timeout 300s -p 1 -tags=integration -coverprofile=coverage.txt ./...
      - run: bash <(curl -s https://codecov.io/bash)

  "lint":
    docker:
      - image: golangci/golangci-lint:v1.12
    working_directory: /go/src/github.com/mesg-foundation/core
    steps:
      - checkout
      - run: golangci-lint run

  "publish_docker_dev":
    <<: *runOnMachine
    steps:
      - checkout
      - run: docker build -t mesg/core:dev --build-arg version="dev build `echo $CIRCLE_SHA1 | cut -c1-7`" .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push mesg/core:dev

  "publish_docker_prod":
    <<: *runOnMachine
    steps:
      - checkout
      - run: docker build -t mesg/core:$CIRCLE_TAG -t mesg/core:latest --build-arg version=$CIRCLE_TAG .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push mesg/core:$CIRCLE_TAG
      - run: docker push mesg/core:latest

  "release_cli_dev":
    <<: *runOnDocker
    steps:
      - checkout
      - run: scripts/build-cli.sh "dev build `echo $CIRCLE_SHA1 | cut -c1-7`"
      - run: go get -u github.com/tcnksm/ghr
      - run: ghr -u mesg-foundation -r core -delete -prerelease -n "Developer Release" -b "Warning - this is a developer release, use it only if you know what are doing. Make sure to pull the latest \`mesg/core:dev\` image. \`\`\`docker pull mesg/core:dev\`\`\`" release-dev ./bin

  "release_cli_prod":
    <<: *runOnDocker
    steps:
      - checkout
      - run: scripts/build-cli.sh $CIRCLE_TAG
      - run: go get -u github.com/tcnksm/ghr
      - run: ghr -u mesg-foundation -r core -delete $CIRCLE_TAG ./bin

workflows:
  version: 2

  pull_request:
    jobs:
      - "lint":
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore:
                - "dev"
                - "master"
      - "test":
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore:
                - "dev"
                - "master"

  release_dev:
    jobs:
      - "test":
          filters:
            tags:
              ignore: /.*/
            branches:
              only: dev
      - "publish_docker_dev":
          requires:
            - "test"
      - "release_cli_dev":
          requires:
            - "publish_docker_dev"

  test_prod:
    jobs:
      - "test":
          filters:
            tags:
              ignore: /.*/
            branches:
              only: master

  release_prod:
    jobs:
      - "test":
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - "publish_docker_prod":
          requires:
            - "test"
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - "release_cli_prod":
          requires:
            - "publish_docker_prod"
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
